DROP TABLE IF EXISTS OrderDiscounts;
DROP TABLE IF EXISTS ApplicableCategories;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS DiscountCodes;
DROP TABLE IF EXISTS Categories;
